import sqlite3
con = sqlite3.connect("Turguid.sql")
cur = con.cursor()
cur.execute("CREATE TABLE movie(title, year, score)")
res = cur.execute("SELECT name FROM sqlite_master")
res.fetchone()
con.commit()
res = cur.execute("SELECT score FROM movie")
res.fetchall()
print(res) 
print("TEST")