@startuml name vetle
'https://plantuml.com/use-case-diagram

left to right direction
:Bruker: --> (Søke etter opplevelse)
:Bruker: --> (Kunne gi rating)
:Bruker: --> (Bestille opplevelse)
:Bruker: --> (Betale for opplevelse)
:Bruker: --> (Lagre opplevelse)

(Se hvor mange som har kjøpt opplevelse) <-- :Admin: 
(Slette opplevelse fra tjeneste) <-- :Admin:
(Legge til ny opplevelse) <-- :Admin:


@enduml