@startuml name vetle
'https://plantuml.com/use-case-diagram

left to right direction
:Bruker: --> (Søke etter opplevelse)
:Bruker: --> (Lagre opplevelse)
:Bruker: --> (Bestille opplevelse)
:Bruker: --> (Betale for opplevelse)
:Bruker: --> (Kunne gi rating)


@enduml