@startuml

left to right direction

:Admin: --> (Se opprettet opplevelser)
:Admin: --> (Legge til ny opplevelse)
:Admin: --> (Slette opplevelse fra tjeneste)
:Admin: --> (Se betalinger for opplevelse)


@enduml