@startuml oppgave1
left to right direction
:Bruker: --> (Bestille opplevelse) 

:Bruker: --> (Betale for opplevelse)
(Betale for opplevelse) --> (Betale med vipps)
(Betale for opplevelse) --> (Betale med kort)
:Bruker: --> (Lagre opplevelse i favoritter)

:Bruker: --> (Søke etter opplevelse)
:Bruker: --> (Logge in/ut)
:Bruker: --> (Få ordrebekreftelse/kvitering på mail)
:Bruker: --> (Kontakte brukerstøtte)

:Bruker: --> (Opprette opplevelse)
:Bruker: --> (Redigere opplevelse)
:Bruker: --> (Slette opplevelse)


(Opprette opplevelse) <-- :Admin:
(Redigere opplevelse) <-- :Admin:
(Blokkere brukere) <-- :Admin:
(Se ordrehistorikk) <-- :Admin:
(Logge in/ut) <-- :Admin:
(Slette opplevelse) <-- :Admin:

@enduml
PlantUML-kildekode til for use caset
